### ISSUE TITLE
Metrics don't work when running tests on windows with runningApplicationPort

### ISSUE THREAD

**Issue by vlad-karnauch** [wixplosives/engine#1044]
Metrics don't work when running tests on windows with runningApplicationPort
## Description
When running tests **on windows**, and using `withFeature` with `runningApplicationPort`, it looks like no marks are registered for metrics. 

Note that the issue works with any tests that uses `getMetric` returned by `getLoadedFeature`, not just the one described in the following 'Steps to Reproduce` Section.

## Expected Behavior
Tests pass (obviously)

## Current Behavior
We get 
```
         measures.marks.push(...(JSON.parse(workerEntries.marks) as PerformanceEntry[]));
                        ^

TypeError: Cannot read properties of undefined (reading 'push')
```

## Steps to Reproduce (for bugs)
on windows, in `...` dir: 
1. run `yarn start` on  your project
2. go to a test file file that uses `getLoadedFeature` and `getMetrics`
3. add 'runningApplicationPort: 3000` to `withFeature` parameters
4. run `cd ...`
5. run `yarn mocha .\dist\test\... (your test file)`

you will see the aforementioned issue in the test results

**## Environment
Windows**

**Comment by RomanYarik** [comment]
fixed at https://github.com/wixplosives/engine/pull/1062
