### ISSUE TITLE
Suggestion: Feature dependencies node graph

### ISSUE THREAD

**Issue by JoMarton** [wixplosives/engine#108]
Hey,
I would like to easily see the dependencies between features in a node graph format like this:

![image](https://user-images.githubusercontent.com/18241740/73657927-ef7c5700-469b-11ea-979b-ef6ac8cfb9d0.png)

Ideally by defining my feature entry point.

Extra points:

Additional data like feature environments, feature API, Config, links and more!!!!

**Comment by AdamYahid** [comment]
Already exists in dashboard
