### ISSUE TITLE
Adopt to new react 18 features

### ISSUE THREAD

**Issue by barak007** [wixplosives/engine#1247]
* Use `react-dom/client` entry point
* Update react types
* Use `createRoot`

**Comment by xeonstaff** [comment]
I'd love to help. Recently built a React 18 app. Do you just want these 3 fixes or...you're upgrading everything?

**Comment by barak007** [comment]
These are the main features we don't use a lot of react here only examples so I don't expect any other changes

**Comment by AviVahl** [comment]
fixed by 53a525ac128236d647d22406c22765ea8dbf1e94
