### ISSUE TITLE
Favicon support

### ISSUE THREAD

**Issue by danielstro** [wixplosives/engine#168]
We want to be able to customize the favicon. Whether we have a path or an actual icon, we are unable to tell the engine to use it.

Regarding Electron, I am not sure how it works but the idea is the same, we want to be able to customize the app's icon.

**Comment by AviVahl** [comment]
You might be able to use the existing engine config's route configuration to do it quickly in the first phase.

@RomanYarik does the route handling work for files as well?

Thinking how to solve the wider issue, I get to questions regarding feature-specific assets and/or `engine.config.js` files.

**Comment by AviVahl** [comment]
steps to resolve:
1. allows specifying `faviconPath` in `engine.config.js`.
2. use that path, if specified, when calling `new HtmlWebpackPlugin({favicon})` in the different flows. (start vs. build; "default" vs "external)
