### ISSUE TITLE
engine test command 

### ISSUE THREAD

**Issue by tomermes** [wixplosives/engine#23]
Moved from scalable:
https://github.com/wixplosives/scalable/issues/283

We need to add the 'engine test' script which will replace the yarn test scripts.

The command should support the following arguments:

path - path of the folder of test file or folder (default value - cwd)
flavor - whether its an ix or spec test
env - whether run tests on node or browser
debug - whether should pause on breakpoints
watch - whether run test once or multiple times
Also need to update readme.md file in engine-scripts to include all possible engine commands and all possible arguments for each command

**Comment by RomanYarik** [comment]
not relevant. no need to wrap mocha...
