### ISSUE TITLE
Communication timeout is too small

### ISSUE THREAD

**Issue by tomermes** [wixplosives/engine#25]
There are some request that going through the communication service, that should not timeout in 5 seconds (importing git assets and dependencies for an example).

Expected Behavior
No timeout error when making long async calls to different environments

Current Behavior
after 5 seconds the request handler dies and when the response returns, it has no handler to handle it.

Proposed fix
const someAsyncFunction = async () => {...}
COM.setCustomTimeout(someAsyncFunction, 20000) // for someAsyncFunction handler, the timeout will be 20 seconds instead of 5 every time it will be called.

**Comment by tomermes** [comment]
(Moved from other repo)

**Comment by RomanYarik** [comment]
solved
