### ISSUE TITLE
AsyncApi inferring types strangely

### ISSUE THREAD

**Issue by Zombiefruit** [wixplosives/engine#571]
Here's a stripped down example: [here](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wMoFEBKA1ASQGEsB9IgeQDkAxAgcTgF44MBPAWwCMIAbAOgBm0ABQByUqSxV6BKmVLZ8xMpVoMxASgDcAKFCRYcGGzDBWwKADcAlgmBEUgmwHMAPABU4oGMGQATVDgAbzgAbSVCEnJqOnoAXQB+AC44AENkNjgAXwA+ZjgPMJMzCEFWXCjVWIZ4vQNoeBLzAFkAV14YGw8MvxgABSgIEDYaNuQELpRPbxBfAKDQiMqVGPUElPTMnIAaOABpWfnAuHQoG2QXfJYcYBg2qGQPU2A3XTgPi2s7BydXT1yYX28V0gLEYCGIzGEymyDEdV0+nAjWMLzgeDSvDawEGEA4NlQrxw1zgOCOfhOuPxhLc4wA1sgIAB3ZD5RKkuCpKkEom5PS6ZpwACCqDYEyFYBsAIKwXenzC-TgFzgdOAbDKhXiXPJCxVao1GEstnsjmQzncHlycs+n3Z7U63V6yAGkNG40mNmmHj2ip8FKCZwuLjg7MVqWQwCslitNptqSK-XiOpOIn4abSUBcqFSF0ElmFmdQmmY+Vz+Zw1tj7NT6cLqSFheLTHyGKxOKG1N5lbjcAjUagemy-IuviggjS9lYeOAEpsIUrqGnLTuAAsIP5UiIm-keHxgBltHAAPRHuAAdRXfjgYDSqEJ-mMEGFovFkr2qDXHQfFLgbTAcC4YAg03bc4G5Gld14fdWV0bJESQNAmhXYDnzFBBZzcDBp1nElZRtE9WE-XgHyZaA6QXJdV3XECS17YAmTAjseRELdaPHXhCU0HZYKAA).

Not sure exactly what is happening here, but something seems to be getting lost in translation.

**Comment by AviVahl** [comment]
`new Promise(() => false)`?
you mean `Promise.resolve(false)`?

**Comment by Zombiefruit** [comment]
> `new Promise(() => false)`?
> you mean `Promise.resolve(false)`?

I don't know what's wrong with me, I keep thinking I can do this. Anyhow, `Promise.resolve(false)` works but `new Promise((res) => res(false))` doesn't.

**Comment by AviVahl** [comment]
If you use `new Promise`, you need to give it an explicit type parameter- `new Promise<boolean>`.
There's a separate bug in the inference there, where it infers `Promise<false> | Promise<true>`. So that's probably a bug.

**Comment by Zombiefruit** [comment]
Ah, makes sense. Okay, closing.

**Comment by AviVahl** [comment]
there's the separate issue... I'll have a PR soon
