### ISSUE TITLE
exposing browser for usage in ix tests

### ISSUE THREAD

**Issue by PeterShershov** [wixplosives/engine#82]
We should consider adding `browser` to `getLoadedFeature` return value for usage in ix tests (i.e `browser.pages()`).

**Comment by RomanYarik** [comment]
Why do we need to access multiple pages in the browser? 
if you want to create a page, or to go to a page, you should work with the specific page reference, no?

**Comment by PeterShershov** [comment]
For testing if a correct URL was opened in a new tab for example.

**Comment by AviVahl** [comment]
For tests that open a new page, one can:.
```ts
const [[newlyOpenedPage]] = await Promise.all([once(page, 'popup') as Promise<[Page]>, page.click('.open-page-button')]);
```
- `Promise.all` to start listening right before making the action.
- `once` is imported from the node `events` api.
- double array destructuring. :P
- exposing the `browser` itself would block us from reusing the same instance by (future) parallel tests. I rather we keep it hidden from test-kit consumers unless we have to expose it.

**Comment by AviVahl** [comment]
Can we close this?

**Comment by PeterShershov** [comment]
Yes.
